// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int numberOfTestsToRun = Integer.parseInt(args[0]);
		double ratioOfRandomness=0, greaterThanOrEq5=0, lessThanOrEq5=0;
		for (int i = 0; i < numberOfTestsToRun; i++) {
			double resultOfRandom = Math.random();
			if (resultOfRandom <= 0.5) {
				lessThanOrEq5++;
			} else {
				greaterThanOrEq5++;
			}
		}
		if (lessThanOrEq5 == 0 || greaterThanOrEq5 == 0) {
			System.out.println("> 0.5: " + (int) greaterThanOrEq5);
			System.out.println("<= 0.5: " + (int) lessThanOrEq5);
		} else {
			ratioOfRandomness = (lessThanOrEq5 > greaterThanOrEq5) ? (greaterThanOrEq5/lessThanOrEq5) : (lessThanOrEq5/greaterThanOrEq5);
			System.out.println("> 0.5: " + (int) greaterThanOrEq5);
			System.out.println("<= 0.5: " + (int) lessThanOrEq5);
			System.out.println("Ratio: " + ratioOfRandomness);
		}
	}
}
